export const MODULE_ID = "pf2e-reactive-token-ring";
// Define color constants
export const COLORS = {
  GREEN: "#ADFF2F",
  RED: "#FF0000",
  YELLOW: "#FFFF00",
  PURPLE: "#9370DB",
  WHITE: "#FFFFFF",
  DEEPSKYBLUE: "#00BFFF",
  ORANGE: "#FFA500",
  PINK: "#FF69B4",
  MAGENTA: "#A612D4",
  PLAYER_DEFAULT: "#FFFFFE",
  PF2E: {
    LEVELDIFF: {
      DEFAULT: {
        "-4": "#bac6df",
        "-3": "#aae1e0",
        "-2": "#97e4ad",
        "-1": "#ace883",
        0: "#eee16e",
        "+1": "#dc9251",
        "+2": "#ba3f39",
        "+3": "#751575",
        "+4": "#231529",
      },
    },
  },
  RANDOM: [
    "#ff0000",
    "#ff6400",
    "#ffc800",
    "#d0ff00",
    "#6cff00",
    "#07ff00",
    "#00ff5c",
    "#00ffc0",
    "#00d8ff",
    "#0074ff",
    "#000fff",
    "#5400ff",
    "#b800ff",
    "#ff00e0",
    "#ff007c",
    "#ff0017",
  ],
};
export const CONDITIONS = {
  POSITIVE: ["concealed", "hidden", "invisible", "quickened", "undetected"],
  NEGATIVE: [
    "blinded",
    "clumsy",
    "confused",
    "controlled",
    "dazzled",
    "deafened",
    "doomed",
    "drained",
    "dying",
    "encumbered",
    "enfeebled",
    "fascinated",
    "fatigued",
    "fleeing",
    "frightened",
    "grabbed",
    "immobilized",
    "off-guard",
    "paralyzed",
    "persistent-damage",
    "petrified",
    "prone",
    "restrained",
    "sickened",
    "slowed",
    "stunned",
    "stupefied",
  ],
  DEAD: ["dead", "unconscious", "wounded"],
};
